### ISSUE TITLE
Detect-changes workflow references secret that no longer exists (and is not needed)

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#1437]

**Comment by shahzadlone** [comment]
For indexability we need to remove this block:
```
  # We need SSH Authorization because change detection needs use `ls-remote` like:
  #  git ls-remote git@github.com:sourcenetwork/defradb.git refs/heads/develop
  - uses: webfactory/ssh-agent@v0.7.0
    with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        log-public-key: false
```

from the `.github/workflows/detect-change.yml` file
