### ISSUE TITLE
The `latest` docker image for `ghcr.io` points to `v0.7.0` not to actual latest

### ISSUE THREAD

**Issue by shahzadlone** [sourcenetwork/defradb#2332]
Docker Pull `latest` for `ghcr.io` points to `v0.7.0`

`docker pull ghcr.io/sourcenetwork/defradb:latest`

Interesting enough, In our last Release Workflow `#4` (https://github.com/sourcenetwork/defradb/actions/runs/7574444222):

The Job [Pull docker image job (sourcenetwork/defradb:latest)](https://github.com/sourcenetwork/defradb/actions/runs/7574444222/job/20629177931#logs)
- Actually pulls the correct latest image(v0.9.0): `sha256:7f3444422c36303fc675a4b1e972d143cabec58f13e63e7a1dc9e5cde2208ca3`

But,

The Job [Pull docker image job (ghcr.io/sourcenetwork/defradb:latest)](https://github.com/sourcenetwork/defradb/actions/runs/7574444222/job/20629178641#logs)
- Pulls the wrong latest image (v0.7.0): `sha256:bbd65fe6e6e6f623edac97672783fee300e4279a328f2080962aca5f3009f8c1`

This is probably because `latest` is on `v0.7.0` release not the actual latest:
https://github.com/sourcenetwork/defradb/pkgs/container/defradb

Here is the latest tag:
https://github.com/sourcenetwork/defradb/pkgs/container/defradb/129070566?tag=latest

Context, we pull in `https://github.com/sourcenetwork/defradb/blob/develop/.github/workflows/release.yml`:

``` yaml
 pull-docker-image:
    name: Pull docker image job
    runs-on: ubuntu-latest
    needs: prepare

    strategy:
      fail-fast: false
      matrix:
        image_tag:
          - sourcenetwork/defradb:latest
          - ghcr.io/sourcenetwork/defradb:latest
```

### Solution:
Seems like with github you just need to push to release tag manually, it then overwrites the previous latest tag to the correct latest one. https://github.com/orgs/community/discussions/23606

Although `https://api.github.com/repos/sourcenetwork/defradb/releases/latest` points to correct version, so I am guessing that `make_latest: true` is set properly in the `.goreleaser.yaml` file, nonetheless can try explicitly setting it, like in: https://goreleaser.com/customization/release/
```
  # If set to false, will NOT mark the release as "latest".
  # This prevents it from being shown at the top of the release list,
  # and from being returned when calling https://api.github.com/repos/OWNER/REPO/releases/latest.
  #
  # Available only for GitHub.
  #
  # Default is true.
  # Since: v1.20
  make_latest: true
```

Bonus Reads:
- https://docs.docker.com/engine/reference/commandline/image_push/#push-a-new-image-to-a-registry
- https://docs.docker.com/engine/reference/commandline/image_push/#all-tags
